# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
# BASED ON c:\Users\aj4775\Workspace\Git\CFA_RTOS\RTOSandModulesTest\Secure

function(add_st_target_properties TARGET_NAME)

target_compile_definitions(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:USE_HAL_DRIVER>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:STM32L552xx>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:USE_FULL_LL_DRIVER>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:USE_HAL_DRIVER>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:STM32L552xx>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:USE_FULL_LL_DRIVER>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:USE_HAL_DRIVER>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:STM32L552xx>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:USE_FULL_LL_DRIVER>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:USE_HAL_DRIVER>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:STM32L552xx>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:USE_FULL_LL_DRIVER>"
)

target_include_directories(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/..\\Secure_nsclib>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/..\\Drivers\\CMSIS\\Device\\ST\\STM32L5xx\\Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/..\\Drivers\\STM32L5xx_HAL_Driver\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/..\\Drivers\\STM32L5xx_HAL_Driver\\Inc\\Legacy>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/..\\Drivers\\CMSIS\\Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/..\\Middlewares\\Third_Party\\FreeRTOS\\Source\\portable\\GCC\\ARM_CM33\\secure>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/..\\Middlewares\\Third_Party\\FreeRTOS\\Source\\portable\\GCC\\ARM_CM33\\non_secure>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/..\\Secure_nsclib>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/..\\Drivers\\CMSIS\\Device\\ST\\STM32L5xx\\Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/..\\Drivers\\STM32L5xx_HAL_Driver\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/..\\Drivers\\STM32L5xx_HAL_Driver\\Inc\\Legacy>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/..\\Drivers\\CMSIS\\Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/..\\Middlewares\\Third_Party\\FreeRTOS\\Source\\portable\\GCC\\ARM_CM33\\secure>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/..\\Middlewares\\Third_Party\\FreeRTOS\\Source\\portable\\GCC\\ARM_CM33\\non_secure>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/..\\Secure_nsclib>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/..\\Drivers\\CMSIS\\Device\\ST\\STM32L5xx\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/..\\Drivers\\STM32L5xx_HAL_Driver\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/..\\Drivers\\STM32L5xx_HAL_Driver\\Inc\\Legacy>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/..\\Drivers\\CMSIS\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/..\\Middlewares\\Third_Party\\FreeRTOS\\Source\\portable\\GCC\\ARM_CM33\\secure>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/..\\Middlewares\\Third_Party\\FreeRTOS\\Source\\portable\\GCC\\ARM_CM33\\non_secure>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/..\\Secure_nsclib>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/..\\Drivers\\CMSIS\\Device\\ST\\STM32L5xx\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/..\\Drivers\\STM32L5xx_HAL_Driver\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/..\\Drivers\\STM32L5xx_HAL_Driver\\Inc\\Legacy>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/..\\Drivers\\CMSIS\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/..\\Middlewares\\Third_Party\\FreeRTOS\\Source\\portable\\GCC\\ARM_CM33\\secure>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/..\\Middlewares\\Third_Party\\FreeRTOS\\Source\\portable\\GCC\\ARM_CM33\\non_secure>"
)

target_compile_options(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:-g3>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:-g3>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:-g3>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:ASM>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-Os>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-Os>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:-mcmse>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:-mcmse>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-mcmse>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-mcmse>"
    "$<$<CONFIG:Debug>:-mcpu=cortex-m33>"
    "$<$<CONFIG:Debug>:-mfpu=fpv5-sp-d16>"
    "$<$<CONFIG:Debug>:-mfloat-abi=hard>"
    "$<$<NOT:$<CONFIG:Debug>>:-mcpu=cortex-m33>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfpu=fpv5-sp-d16>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfloat-abi=hard>"
)

target_link_libraries(
    ${TARGET_NAME} PRIVATE
)

target_link_directories(
    ${TARGET_NAME} PRIVATE
)

target_link_options(
    ${TARGET_NAME} PRIVATE
    "$<$<CONFIG:Debug>:-mcpu=cortex-m33>"
    "$<$<CONFIG:Debug>:-mfpu=fpv5-sp-d16>"
    "$<$<CONFIG:Debug>:-mfloat-abi=hard>"
    "$<$<NOT:$<CONFIG:Debug>>:-mcpu=cortex-m33>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfpu=fpv5-sp-d16>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfloat-abi=hard>"
    -T
    "$<$<CONFIG:Debug>:${PROJECT_SOURCE_DIR}/STM32L552ZETXQ_FLASH.ld>"
    "$<$<NOT:$<CONFIG:Debug>>:${PROJECT_SOURCE_DIR}/STM32L552ZETXQ_FLASH.ld>"
    "$<$<CONFIG:Debug>:SHELL:-Wl$<COMMA>--cmse-implib>"
    "$<$<CONFIG:Debug>:SHELL:-Wl$<COMMA>--out-implib=secure_nsclib.o>"
    "$<$<NOT:$<CONFIG:Debug>>:SHELL:-Wl$<COMMA>--cmse-implib>"
    "$<$<NOT:$<CONFIG:Debug>>:SHELL:-Wl$<COMMA>--out-implib=secure_nsclib.o>"
)

target_sources(
    ${TARGET_NAME} PRIVATE
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_cortex.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_dma.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_dma_ex.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_exti.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_flash.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_flash_ex.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_flash_ramfunc.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_gpio.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_gtzc.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_hash.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_hash_ex.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_i2c.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_i2c_ex.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_icache.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_pcd.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_pcd_ex.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_pwr.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_pwr_ex.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rcc.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rcc_ex.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rng.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rng_ex.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rtc.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rtc_ex.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_tim.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_tim_ex.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_uart.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_uart_ex.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_ll_dma.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_ll_exti.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_ll_gpio.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_ll_ucpd.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_ll_usb.c"
    "../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_ll_utils.c"
    "../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/secure/secure_context.c"
    "../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/secure/secure_context_port.c"
    "../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/secure/secure_heap.c"
    "../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/secure/secure_init.c"
    "Core\\Src\\add2buff.c"
    "Core\\Src\\cfa.c"
    "Core\\Src\\device_ops.c"
    "Core\\Src\\dispatcher.c"
    "Core\\Src\\hash.c"
    "Core\\Src\\main.c"
    "Core\\Src\\messages.c"
    "Core\\Src\\rtpox_cs.c"
    "Core\\Src\\rtpox.c"
    "Core\\Src\\secure_nsc.c"
    "Core\\Src\\secure_terminal.c"
    "Core\\Src\\stm32l5xx_hal_msp.c"
    "Core\\Src\\stm32l5xx_it.c"
    "Core\\Src\\stringop.c"
    "Core\\Src\\syscalls.c"
    "Core\\Src\\sysmem.c"
    "Core\\Src\\system_stm32l5xx_s.c"
    "Core\\Src\\terminal_calls.c"
    "Core\\Src\\test.c"
    "Core\\Startup\\startup_stm32l552zetxq.s"
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_SIZE} $<TARGET_FILE:${TARGET_NAME}>
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O ihex
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.hex
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O binary
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.bin
)

endfunction()